In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('C:\\Users\\1933958\\Desktop\\DataScience\\ohana-api-master\\data\\sample-csv\\taxonomy.csv',sep=',',skiprows=[1,3])

In [3]:
df

taxonomy_id                          name parent_id           parent_name
0        101-01             Disaster Response       101             Emergency
1     101-02-01             Help Pay for Food    101-02        Emergency Cash
2     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
3     101-02-03          Help Pay for Housing    101-02        Emergency Cash
4     101-02-04              Help Pay for Gas    101-02        Emergency Cash
..          ...                           ...       ...                   ...
283   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
284      111-02                     Mediation       111                 Legal
285      111-03                        Notary       111                 Legal
286      111-04                Representation       111                 Legal
287      111-05  Translation & Interpretation       111                 Legal

[288 rows x 4 columns]

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df2=pd.read_csv('C:\\Users\\1933958\\Desktop\\DataScience\\ohana-api-master\\data\\sample-csv\\services.csv')

In [6]:
df2.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [7]:
df2.head(3)

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   
2   3            3         NaN               NaN            NaN   

                           application_process  \
0                   Walk in or apply by phone.   
1           Apply by phone for an appointment.   
2  Phone for information (403-4300 Ext. 4322).   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   
2  Offers supportive counseling services to San M...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   
2        Resident of San Mateo County age 55 or over   NaN  ...   

  interpretation_services                                           keywords  \
0                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...   
1                     NaN  EMPLOYMENT/TRAINING SERVICES, Job Development,...   
2                     NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...   

  languages                              name required_documents  \
0       NaN   Fair Oaks Adult Activity Center                NaN   
1       NaN  Second Career Employment Program                NaN   
2       NaN            Senior Peer Counseling                NaN   

      service_areas  status wait_time website taxonomy_ids  
0             Colma  active  No wait.     NaN          NaN  
1  San Mateo County  active   Varies.     NaN          NaN  
2  San Mateo County  active   Varies.     NaN          NaN  

[3 rows x 22 columns]

In [8]:
df.tail(10)

taxonomy_id                            name parent_id  \
278   111-01-02       Citizenship & Immigration    111-01   
279   111-01-03   Discrimination & Civil Rights    111-01   
280   111-01-04                    Guardianship    111-01   
281   111-01-05         Identification Recovery    111-01   
282   111-01-06  Understand Government Programs    111-01   
283   111-01-07                Workplace Rights    111-01   
284      111-02                       Mediation       111   
285      111-03                          Notary       111   
286      111-04                  Representation       111   
287      111-05    Translation & Interpretation       111   

              parent_name  
278  Advocacy & Legal Aid  
279  Advocacy & Legal Aid  
280  Advocacy & Legal Aid  
281  Advocacy & Legal Aid  
282  Advocacy & Legal Aid  
283  Advocacy & Legal Aid  
284                 Legal  
285                 Legal  
286                 Legal  
287                 Legal

In [9]:
df.columns

Index(['taxonomy_id', 'name', 'parent_id', 'parent_name'], dtype='object')

In [10]:
df.dtypes

taxonomy_id    object
name           object
parent_id      object
parent_name    object
dtype: object

In [11]:
df[['taxonomy_id','name','parent_id']]


taxonomy_id                          name parent_id
0        101-01             Disaster Response       101
1     101-02-01             Help Pay for Food    101-02
2     101-02-02       Help Pay for Healthcare    101-02
3     101-02-03          Help Pay for Housing    101-02
4     101-02-04              Help Pay for Gas    101-02
..          ...                           ...       ...
283   111-01-07              Workplace Rights    111-01
284      111-02                     Mediation       111
285      111-03                        Notary       111
286      111-04                Representation       111
287      111-05  Translation & Interpretation       111

[288 rows x 3 columns]

In [12]:
a=df['name']

In [13]:
type(a)
a

0                 Disaster Response
1                 Help Pay for Food
2           Help Pay for Healthcare
3              Help Pay for Housing
4                  Help Pay for Gas
                   ...             
283                Workplace Rights
284                       Mediation
285                          Notary
286                  Representation
287    Translation & Interpretation
Name: name, Length: 288, dtype: object

In [14]:
b=df[['taxonomy_id','name','parent_id']]


In [15]:
type(b)

pandas.core.frame.DataFrame

In [16]:
c=df[['taxonomy_id']]
c

taxonomy_id
0        101-01
1     101-02-01
2     101-02-02
3     101-02-03
4     101-02-04
..          ...
283   111-01-07
284      111-02
285      111-03
286      111-04
287      111-05

[288 rows x 1 columns]

In [17]:
df3=pd.read_excel('LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx',sheet_name='Introduction')
df3

Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  \
0          NaN         NaN         NaN         NaN   
1          NaN         NaN         NaN         NaN   
2          NaN         NaN         NaN         NaN   
3          NaN         NaN         NaN         NaN   
4          NaN         NaN         NaN         NaN   
5          NaN         NaN         NaN         NaN   
6          NaN         NaN         NaN         NaN   
7          NaN         NaN         NaN         NaN   
8          NaN         NaN         NaN         NaN   
9          NaN         NaN         NaN         NaN   
10         NaN         NaN         NaN         NaN   
11         NaN         NaN         NaN         NaN   
12         NaN         NaN         NaN         NaN   
13         NaN         NaN         NaN         NaN   
14         NaN         NaN         NaN         NaN   
15         NaN         NaN         NaN         NaN   
16         NaN         NaN         NaN         NaN   
17         NaN         NaN         NaN         NaN   
18         NaN         NaN         NaN         NaN   
19         NaN         NaN         NaN         NaN   
20         NaN         NaN         NaN         NaN   
21         NaN         NaN         NaN         NaN   
22         NaN         NaN         NaN         NaN   
23         NaN         NaN         NaN         NaN   
24         NaN         NaN         NaN         NaN   
25         NaN         NaN         NaN         NaN   
26         NaN         NaN         NaN         NaN   
27         NaN         NaN         NaN         NaN   
28         NaN         NaN         NaN         NaN   
29         NaN         NaN         NaN         NaN   
30         NaN         NaN         NaN         NaN   
31         NaN         NaN         NaN         NaN   
32         NaN         NaN         NaN         NaN   
33         NaN         NaN         NaN         NaN   

                                           Unnamed: 4  
0                                                 NaN  
1                                                 NaN  
2                                                 NaN  
3                                                 NaN  
4                                                 NaN  
5                                                 NaN  
6                                                 NaN  
7                                                 NaN  
8                                                 NaN  
9                                                 NaN  
10                                                NaN  
11                                                NaN  
12                                                NaN  
13                                      The Challenge  
14                                                NaN  
15  You are an asset manager who has recently secu...  
16                                                NaN  
17  As part of the investment agreement with the p...  
18                                                NaN  
19                                       The Solution  
20                                                NaN  
21  Using LUSID you can mirror your live investmen...  
22                                                NaN  
23  1) Creating your live production environment f...  
24                                                NaN  
25               2) Creating your instrument universe  
26                                                NaN  
27  3) Adding your take on balances for your clien...  
28                                                NaN  
29  4) Creating your test environment and using de...  
30                                                NaN  
31  5) Making some trades for your client in your ...  
32                                                NaN  
33  6) Adding some transactions to your test envir...

In [18]:
df4=pd.ExcelFile('LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx')
df4.sheet_names

['Create Portfolio',
 'Introduction',
 'Create your instrument universe',
 'Add your take on balances',
 'Create your test environment',
 'Make live trades in production',
 'Add some test transactions',
 'Inputs']

In [19]:
for i in df.sheet_names:
    pd.read_csv('LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx',sheet_name=i)

AttributeError: 'DataFrame' object has no attribute 'sheet_names'

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

# Day2 

In [ ]:
pip install lxml

In [ ]:

//extrct tabular data only 
pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [ ]:
df.to_csv('Adman.csv',index=False,header=False)

In [ ]:
pd.read_html('https://stats.espncricinfo.com/ci/engine/records/averages/batting.html?class=2;id=2020;type=year')

In [ ]:
d="""
{
"name": "Adnan",
"email": "xyz@gmail.com",
"tech": ["ML", "DL", "DA"],
"platform": ["A", "B", "C"]
}
"""

In [ ]:
import json

In [ ]:
res=json.loads(d)

In [ ]:
res

In [ ]:
type(res)

In [ ]:
result=pd.DataFrame(res)

In [ ]:
res['name']

In [ ]:
res['tech']

In [ ]:
pd.DataFrame(res['name'])

In [ ]:
pd.DataFrame(res['tech'])

In [ ]:
# del df['xyz colm']  if any mismqtch in list length

In [ ]:
data={ 
    "coffee": {
        "region": [
            {"id":1,"name":"John Doe"},
            {"id":2,"name":"Don Joeh"}
        ],
        "country": {"id":2,"company":"ACME"}
    }, 
    "brewing": {
        "region": [
            {"id":1,"name":"John Doe"},
            {"id":2,"name":"Don Joeh"}
        ],
        "country": {"id":2,"company":"ACME"}
    }


}

In [ ]:
x=data['coffee']['region']
x

In [ ]:
pd.DataFrame(x)

In [ ]:
dfNew=pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

In [ ]:
dfNew

In [ ]:
import requests
url="https://api.github.com/repos/pandas-dev/pandas/issues";

In [ ]:
data=requests.get(url)

In [ ]:
data

In [ ]:
data1=data.json()
data1

In [ ]:
# unique Dictionaries
len(data1)

In [ ]:
data1[0]['user']['id']

In [ ]:
for i in range(len(data1)):
    print(data1[i]['user']['id'])

In [ ]:
data1

In [ ]:
pd.DataFrame(data1)

In [ ]:
df2=pd.DataFrame(data1,columns=['id','url','repository_url','labels_url','user'])

In [ ]:
df2.to_csv('JSONRESPONSE.csv')

In [ ]:
df2.head()

In [ ]:
# pd.DataFrame(df2[['user']],columns=['login',id])


In [ ]:
# Challenge

In [ ]:
x=[];
y=[];
for i in range(0,len(df2)):
    x.append(df2['user'][i]['login'])
    y.append(df2['user'][i]['id'])
x
y

In [ ]:
df2['login']=x
df2['user_id']=y
df2

# Day3

In [ ]:
dfTitanic=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
dfTitanic

In [ ]:
dfTitanic.dtypes

In [ ]:
dfTitanic.info()

In [ ]:
dfTitanic.describe()

In [ ]:
dfTitanic['PassengerId'].sum()/891

In [ ]:
dfTitanic.columns

In [ ]:
dfTitanic.dtypes=="object"

In [ ]:
type(dfTitanic.dtypes)

In [ ]:
dfTitanic.dtypes[dfTitanic.dtypes=="object"]

In [ ]:
list=[1,3,4,5,"Adnan","Heman"]


In [ ]:
list[0]

In [ ]:
list[list==4]

In [ ]:
col_name=dfTitanic.dtypes[dfTitanic.dtypes=="object"].index

In [ ]:
col_name

In [ ]:
dfTitanic[col_name].describe()

In [ ]:
dfTitanic['Ineuron']="Adnan"

In [ ]:
dfTitanic

In [ ]:
dfTitanic['Name'][0:15]

In [ ]:
dfTitanic['Name'][0:15:2]

In [ ]:
dfTitanic['Name'][15:0:-1]

In [ ]:
dfTitanic[dfTitanic["Age"].isnull()==True]

In [ ]:
age_null_indexes=dfTitanic[dfTitanic["Age"].isnull()==True].index
age_null_indexes

In [ ]:
dfTitanic.loc[age_null_indexes]

In [ ]:
dfTitanic['Fare'].max()

In [ ]:
dfTitanic[dfTitanic['Fare']==dfTitanic['Fare'].max()]['Name'].values

In [ ]:
dfTitanic.head()

In [ ]:
# Challenges

In [ ]:
male=len(dfTitanic[dfTitanic['Sex']=="male"])
# Or

In [ ]:
dfTitanic.groupby('Sex').size()

In [ ]:
female=len(dfTitanic[dfTitanic['Sex']=="female"])
female

In [ ]:
len(dfTitanic[dfTitanic['Survived']==1])

In [ ]:
dfTitanic[dfTitanic['Age']==dfTitanic['Age'].max()]['Name']

In [ ]:
len(dfTitanic[dfTitanic['Pclass']==1])
len(dfTitanic[dfTitanic['Pclass']==2])
len(dfTitanic[dfTitanic['Pclass']==3])


In [ ]:
dfTitanic['Pclass'].value_counts()

In [ ]:
dfTitanic[dfTitanic['Name'].str.startswith('S')]

In [ ]:
dfTitanic.groupby('Pclass')['Pclass'].count()

In [ ]:
dfTitanic['New Column']=dfTitanic['SibSp']+dfTitanic['Parch']

In [ ]:
dfTitanic

In [ ]:
len(dfTitanic[dfTitanic['Age']<25])

In [ ]:
len(dfTitanic[(dfTitanic['Age']<40) &  (dfTitanic['Survived']==0)])


In [ ]:
dfTitanic['Cabin']

In [ ]:
import re
replace=re.compile("([a-zA-Z]+)")

In [ ]:
dfTitanic['srting_cabin']=dfTitanic['Cabin'].str.extract(replace)
dfTitanic['num_cabin']=dfTitanic['Cabin'].str.replace(replace,"")
dfTitanic

In [ ]:
df=pd.read_csv('C:\\Users\\1933958\\Desktop\\DataScience\\bank.csv',sep=';')
df

In [ ]:
# challenge

In [ ]:
len(df['campaign'].unique())

In [ ]:
dfnew =df[(df['housing']=='yes') & (df['loan']=='yes')]

In [ ]:
len(dfnew)

In [ ]:
df['month'].value_counts().index[0]

In [ ]:
dfgroup=df.groupby(['contact','y']).count()
dfgroup

In [ ]:
dfgroup.loc['cellular','yes']
dfgroup.loc['telephone','yes']


In [ ]:
len(df[df['job']=='entrepreneur'])

In [ ]:
len(df[df['balance']<0])

In [ ]:
df.groupby('education')['education'].count()

In [ ]:
df['education'].unique()

In [ ]:
l=[]
for i in df['education'].unique():
    l.append(df[df['education']==i])


In [ ]:
l[0]

In [ ]:
l[1]

# Day 4

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dfTitanic

In [ ]:
dfTitanic.dropna(axis=1)

In [ ]:
dfTitanic.isnull().sum()

In [ ]:
dfTitanic.dropna(axis=1,thresh=800,how ="all")

In [ ]:
dfTitanic.fillna(value="Adnan")

In [ ]:
dfTitanic.fillna(value=dfTitanic['Age'].mean())

In [ ]:
dfTitanic.groupby(['Survived']).describe()

In [ ]:
dfTitanic.groupby(['Survived']).describe()['PassengerId'].transpose()

In [ ]:
df2=df.head(5)
df3=df.tail(5)

In [ ]:
df5=pd.concat([df2,df3],axis=1)
df5

In [ ]:
df5['age']

In [ ]:
df5.iloc[:,[3,4]]

In [ ]:
df5.iloc[[4,5],[3,4]]

In [ ]:
df.loc[[1,4519],'age']

In [ ]:
df2

In [ ]:
df2.iloc[[1,2],[2,3]]

In [ ]:
df2.loc[[1,2],['marital','education']]

In [ ]:
pd.merge(df2,df3,on='age',how="left")

In [ ]:
pd.merge(df2,df3,on='age',how="right")

In [ ]:
pd.merge(df2,df3,on='age',how="outer")

In [ ]:
df2.join(df3,on='age')

In [ ]:
df2=df2.set_index('age')
df2.rename(columns={''})

In [ ]:
df3=df3.set_index('age')

In [ ]:
df2.join(df3,on='age')

# Day5

In [ ]:
df=pd.DataFrame({'col1':[1,2,3,4,5],
               'col2':[23,32,12,34,22],
                'col3':"Syed Mohammad Adnan Mian Sahab".split(" ") })

df

In [ ]:
df['col4']=df['col1']**2
df

In [ ]:
df['col5']=df['col3'].str[0]
df

In [ ]:
def test(a):
    return a**2

In [ ]:
df['col_4']=df['col1'].apply(test)
df

In [ ]:
def test2(val):
    if(val=="S"):
        return "S"
    else:
        return "Z"

In [ ]:
df['col6']=df['col5'].apply(test2)

In [ ]:
df

In [ ]:
df['col6_6']=df['col5'].apply(lambda val:"S" if val=="S" else "Z")

In [ ]:
df

In [ ]:
df['col7']=df['col3'].apply(len)
df

In [ ]:
import math
df['col8']=df['col2'].apply(math.log)

In [ ]:
df

# NUMPY

In [ ]:
import numpy as np

In [ ]:
l=["Adnan",1,3,4,5,6]
type(l)

In [ ]:
a=np.array(l)
a

In [ ]:
type(a)

In [ ]:
c=np.array([3,4,5,6,7.0])
c

In [ ]:
b=np.array([[1,2],[3,4]])
b

In [ ]:
b[1][1]

In [ ]:
c[1]

In [ ]:
d=np.array([1,2,3,4],ndmin=3)
d

In [ ]:
d[0][0][0]

In [ ]:
np.asanyarray([1,2,3,4,5])

In [ ]:
np.asarray([1,2,3,4,5])

In [ ]:
np.mat([1,2,3,4,5])

In [ ]:
a=[1,2,3,4,5,6]
np.asanyarray(a)

In [ ]:
np.mat(a)

In [ ]:
np.asanyarray(np.mat(a))

In [ ]:
np.fromfunction(lambda i,j:i==j ,(3,3))

In [ ]:
np.fromfunction(lambda i,j:i*j ,(4,4),dtype=int)

In [ ]:
y=np.mat(np.fromfunction(lambda i,j:i*j ,(4,4),dtype=int))
y

In [ ]:

z=np.fromfunction(lambda i,j,z:i*j*z ,(3,3,2),dtype=int)
z

In [ ]:
z

In [ ]:
z.ndim

In [ ]:
z.size

In [ ]:
z.shape

In [ ]:
z.dtype

In [ ]:
y=np.mat(np.fromfunction(lambda i,j:i*j ,(400,100),dtype=int))
pd.DataFrame(y)

In [ ]:
x=np.random.rand(100,4)
x

In [ ]:
y=np.random.randint(4,50)
y

In [ ]:
n=np.random.randn(4,5)
n

In [ ]:
pd.DataFrame(n)

In [ ]:
z

In [ ]:
z=z.reshape(6,3)
z

In [ ]:
pd.DataFrame(z)

In [ ]:
z=np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2),dtype=int)
z

In [ ]:
z.reshape(4,-1)

In [ ]:
z.reshape(2,-1)

In [ ]:
z.reshape(2,-102345)

In [ ]:
list(range(4,10,2))

In [ ]:
a1=np.arange(4,10.5,0.2)
a1

In [ ]:
a1[1:4]

In [ ]:
arr=np.random.rand(4,5)
arr

In [ ]:
arr[arr>0.5]

In [ ]:
arr

In [ ]:
arr[1:3,2]

In [ ]:
arr=np.random.rand(8,5)
arr

In [ ]:
a2=arr[1:,0:3]
a2

In [ ]:
a2[0][0]=120
a2

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [ ]:
a

In [ ]:
b

In [ ]:
a*b

In [ ]:
# Matrix Multiplication
m=a@b

In [ ]:
m/0

# NUMPY PART2

In [20]:
import numpy as np

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
a=np.ones((3,5))

In [32]:
pd.DataFrame(a)

0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0

In [35]:
# BroadCasting
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [39]:
np.empty((4,5))

array([[0.e+000, 1.e-323, 0.e+000, 0.e+000, 1.e-323],
       [2.e-323, 3.e-323, 4.e-323, 5.e-323, 6.e-323],
       [0.e+000, 1.e-323, 2.e-323, 3.e-323, 4.e-323],
       [5.e-323, 6.e-323, 7.e-323, 8.e-323, 9.e-323]])

In [43]:
x=np.linspace(2,6,10)
x

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [44]:
x.reshape(2,5)

array([[2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778],
       [4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]])

In [47]:
y=np.linspace(2,6,10,endpoint=False,retstep=True)
y

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [52]:
np.logspace(2,6,10,base=2)

array([ 4.        ,  5.44316   ,  7.4069977 , 10.0793684 , 13.71590373,
       18.66446463, 25.39841683, 34.56191164, 47.03150375, 64.        ])

In [65]:
a=np.arange(0,16).reshape(4,4)
a[2][0]=30
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [30,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
a.max()

15

In [62]:
a.max(axis=1)

array([ 3,  7, 30, 15])

In [64]:
a.max(axis=0)

array([30, 13, 14, 15])

In [66]:
10+a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [40, 19, 20, 21],
       [22, 23, 24, 25]])

In [67]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [900,  81, 100, 121],
       [144, 169, 196, 225]])

In [68]:
pow(a,4)

array([[     0,      1,     16,     81],
       [   256,    625,   1296,   2401],
       [810000,   6561,  10000,  14641],
       [ 20736,  28561,  38416,  50625]], dtype=int32)

In [77]:
b=np.array([2,1,4,3])

In [78]:
a+b

array([[ 2,  2,  6,  6],
       [ 6,  6, 10, 10],
       [32, 10, 14, 14],
       [14, 14, 18, 18]])

In [80]:
b=np.array([2,1,4,3]).T
b

array([2, 1, 4, 3])

In [92]:
b=b.reshape(-1,1)

In [94]:
b=b.T
b

array([[2],
       [1],
       [4],
       [3]])

In [95]:
a+b

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [34, 13, 14, 15],
       [15, 16, 17, 18]])

In [97]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [5.47722558, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [98]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [1.06864746e+13, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [99]:
np.log10(a)

C:\Users\1933958\AppData\Local\Temp/ipykernel_16480/547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [1.47712125, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [100]:
x=np.array([1,2,3])

In [101]:
y=x

In [102]:
y

array([1, 2, 3])

In [103]:
z=np.copy(x)

In [104]:
z

array([1, 2, 3])

In [105]:
x[0]=100

In [106]:
y

array([100,   2,   3])

In [107]:
z

array([1, 2, 3])

In [108]:
id(x)

1762106866640

In [109]:
id(y)

1762106866640

In [110]:
id(z)

1762106866256

In [111]:
id(x[0])

1762107031696

In [112]:
id(y[0])

1762107031664

In [115]:
id(x[0])==id(y[0])

True

In [116]:
c="Adnan"
id(c)==id(x)

False